In [79]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Assignment 1: Working with numpy

In [14]:
#Q1 (a)
arr=np.arange(1,21,1)
arr_sum=np.sum(arr)
print(arr_sum)
arr_mean=np.mean(arr)
print(arr_mean)
arr_median=np.median(arr)
print(arr_median)
arr_std=np.std(arr)
print(arr_std)

210
10.5
10.5
5.766281297335398


In [19]:
#Q1 (b)
for i in range (0,20,1):
    if arr[i]>10:
        print(i)

10
11
12
13
14
15
16
17
18
19


In [40]:
#Q2
arr1=np.arange(1,17).reshape(4,4)
arr_T=np.empty((4,4))
#(a)
print(arr1)
#(b)
for i in range (0,4):
    for j in range(0,4):
       arr_T[i,j]=arr1[j,i]
print(arr_T)
#(c)
row_sum=np.sum(arr1, axis=1)
coloumn_sum=np.sum(arr1,axis=0)
print(row_sum)
print(coloumn_sum)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]
[10 26 42 58]
[28 32 36 40]


In [63]:
#Q3
arr2=np.random.randint(1,20,(3,3))
arr3=np.random.randint(1,20,(3,3))
print(arr2)
print(arr3)
#(a)
for i in range (0,3):
    for j in range (0,3):
        print(arr2[i,j]+arr3[i,j])#Element wise addition
        print(arr2[i,j]*arr3[i,j])#multiplication
        print(arr2[i,j]-arr3[i,j])#substraction
#(b)
print(np.dot(arr2,arr3))

[[14 16  7]
 [ 1  4 15]
 [ 8 15 11]]
[[ 5  4  7]
 [ 9 11  2]
 [15 16  6]]
19
70
9
20
64
12
14
49
0
10
9
-8
15
44
-7
17
30
13
23
120
-7
31
240
-1
17
66
5
[[319 344 172]
 [266 288 105]
 [340 373 152]]


In [78]:
#Q4
arr4=np.arange(1,13).reshape(3,4)
print(arr4)
print("First row: ", arr4[0,:])
print("Second row: ", arr4[1,:])
print("last coloumn: ", arr4[:,-1])
print("second last coloumn: ", arr4[:,-2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row:  [1 2 3 4]
Second row:  [5 6 7 8]
last coloumn:  [ 4  8 12]
second last coloumn:  [ 3  7 11]


### Assignment 2: Working with Pandas

In [81]:
#Q1
df=pd.DataFrame({
      'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
      'Age': [24, 27, 22, 32, 29],
      'Department': ['HR', 'Finance', 'IT', 'Marketing', 'HR'],
      'Salary': [45000, 54000, 50000, 62000, 47000]
})
#(a)
print(df.head(5))
#(b)
print(df['Age'])
print(df['Salary'])
#(c)
print("Average Salary or HR employees: ",df['Salary'].mean())

      Name  Age Department  Salary
0    Alice   24         HR   45000
1      Bob   27    Finance   54000
2  Charlie   22         IT   50000
3    Diana   32  Marketing   62000
4      Eve   29         HR   47000
0    24
1    27
2    22
3    32
4    29
Name: Age, dtype: int64
0    45000
1    54000
2    50000
3    62000
4    47000
Name: Salary, dtype: int64
Average Salary or HR employees:  51600.0


In [82]:
#Q2
df['Bonus']=df['Salary']*0.1
df

,Name,Age,Department,Salary,Bonus
0,Alice,24,HR,45000,4500.0
1,Bob,27,Finance,54000,5400.0
2,Charlie,22,IT,50000,5000.0
3,Diana,32,Marketing,62000,6200.0
4,Eve,29,HR,47000,4700.0


In [83]:
#Q3
filtered_df=df[(df['Age']>25) & (df['Age']<30)]
print(filtered_df)

  Name  Age Department  Salary   Bonus
1  Bob   27    Finance   54000  5400.0
4  Eve   29         HR   47000  4700.0


In [84]:
#Q4
df.groupby('Department')['Salary'].mean()

Department
Finance      54000.0
HR           46000.0
IT           50000.0
Marketing    62000.0
Name: Salary, dtype: float64

In [85]:
#Q5
sorted_df=df.sort_values(by='Salary', ascending=True)
sorted_df.to_csv("Sorted DataFrame.csv", index=True)

### Assignment 3: Working with Matplotlib

In [ ]:
#Q1
x = [1, 2, 3, 4, 5]
y = [10, 15, 25, 30, 50]

plt.plot(x, y)
plt.title("Simple Line Plot")
plt.xlabel("X values")
plt.ylabel("Y values")
plt.grid(True)
plt.show()

In [ ]:
#Q2
students = ['John', 'Jane', 'Alice', 'Bob']
marks = [75, 85, 60, 90]

plt.bar(students, marks, color=['blue', 'green', 'orange', 'red'])
plt.title("Marks Scored by Students")
plt.xlabel("Students")
plt.ylabel("Marks")
plt.show()

In [ ]:
#Q3
regions = ['North America', 'Europe', 'Asia', 'Others']
revenue = [45, 25, 20, 10]

explode = [0.1, 0, 0, 0]  # Highlight North America

plt.pie(revenue, labels=regions, explode=explode, autopct='%1.1f%%', startangle=90)
plt.title("Revenue Distribution by Region")
plt.show()

In [ ]:
#Q4
data = np.random.randint(1, 101, 1000)

plt.hist(data, bins=10)
plt.title("Histogram of Random Integers")
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.show()